# Exercício guiado

### Calcular médias de tendência central e dispersão com Pandas

In [1]:
import pandas as pd

C:\Users\thali\AppData\Local\Temp\ipykernel_42516\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
# web scraping - obter dados de um site
dados = pd.read_html('https://pt.wikipedia.org/wiki/Lista_de_munic%C3%ADpios_do_Brasil_acima_de_cem_mil_habitantes')

In [3]:
pip install lxml

Requirement already satisfied: lxml in c:\users\thali\appdata\local\programs\python\python312\lib\site-packages (5.3.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.3.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
dados
# retornará diversas tabelas

[     Pos       Município Unidade federativa População[1]
 0      1       São Paulo          São Paulo   11 451 999
 1      2  Rio de Janeiro     Rio de Janeiro    6 211 223
 2      3        Brasília   Distrito Federal    2 817 381
 3      4       Fortaleza              Ceará    2 428 708
 4      5        Salvador              Bahia    2 417 678
 ..   ...             ...                ...          ...
 314  315      Manacapuru           Amazonas      101 883
 315  316          Balsas           Maranhão      101 767
 316  317         Lagarto            Sergipe      101 579
 317  318           Assis          São Paulo      101 409
 318  319       Itaperuna     Rio de Janeiro      101 041

 [319 rows x 4 columns],
                            vdeTópicos sobre o Brasil  \
 0                                            Cultura
 1                                           Economia
 2                                          Geografia
 3                                           História
 4                                     Infraestrutura
 5                                           Política
 6  Categoria  Portal do Brasil  WikiProjeto  Commons

                          vdeTópicos sobre o Brasil.1  \
 0  Artes Cinema Culinária Esporte Feriados Filoso...
 1  Agricultura Banco Central Empresas Indústria M...
 2  Biodiversidade Áreas Protegidas Biomas Problem...
 3  Cronologia Periodização Período pré-Cabralino ...
 4  Ciência e Tecnologia Comunicações Educação Ene...
 5  Administração Pública Governo Constituição Dir...
 6  Categoria  Portal do Brasil  WikiProjeto  Commons

                          vdeTópicos sobre o Brasil.2
 0                                                NaN
 1                                                NaN
 2                                                NaN
 3                                                NaN
 4                                                NaN
 5                                                NaN
 6  Categoria  Portal do Brasil  WikiProjeto  Commons  ]

In [5]:
# utilizaremos somente a primeira tabela
dados_populacao = dados[0]
dados_populacao

     Pos       Município Unidade federativa População[1]
0      1       São Paulo          São Paulo   11 451 999
1      2  Rio de Janeiro     Rio de Janeiro    6 211 223
2      3        Brasília   Distrito Federal    2 817 381
3      4       Fortaleza              Ceará    2 428 708
4      5        Salvador              Bahia    2 417 678
..   ...             ...                ...          ...
314  315      Manacapuru           Amazonas      101 883
315  316          Balsas           Maranhão      101 767
316  317         Lagarto            Sergipe      101 579
317  318           Assis          São Paulo      101 409
318  319       Itaperuna     Rio de Janeiro      101 041

[319 rows x 4 columns]

In [6]:
# renomeando os titulos das colunas
dados_populacao.columns = ['ranking', 'municipio', 'uf', 'populacao']
dados_populacao

     ranking       municipio                uf   populacao
0          1       São Paulo         São Paulo  11 451 999
1          2  Rio de Janeiro    Rio de Janeiro   6 211 223
2          3        Brasília  Distrito Federal   2 817 381
3          4       Fortaleza             Ceará   2 428 708
4          5        Salvador             Bahia   2 417 678
..       ...             ...               ...         ...
314      315      Manacapuru          Amazonas     101 883
315      316          Balsas          Maranhão     101 767
316      317         Lagarto           Sergipe     101 579
317      318           Assis         São Paulo     101 409
318      319       Itaperuna    Rio de Janeiro     101 041

[319 rows x 4 columns]

In [7]:
dados_populacao[:20] # as 20 primeiras informações

# outra forma: 
# dados_populacao.head(20)

    ranking       municipio                  uf   populacao
0         1       São Paulo           São Paulo  11 451 999
1         2  Rio de Janeiro      Rio de Janeiro   6 211 223
2         3        Brasília    Distrito Federal   2 817 381
3         4       Fortaleza               Ceará   2 428 708
4         5        Salvador               Bahia   2 417 678
5         6  Belo Horizonte        Minas Gerais   2 315 560
6         7          Manaus            Amazonas   2 063 689
7         8        Curitiba              Paraná   1 773 718
8         9          Recife          Pernambuco   1 488 920
9        10         Goiânia               Goiás   1 437 366
10       11    Porto Alegre   Rio Grande do Sul   1 332 845
11       12           Belém                Pará   1 303 403
12       13       Guarulhos           São Paulo   1 291 771
13       14        Campinas           São Paulo   1 139 047
14       15        São Luís            Maranhão   1 037 775
15       16          Maceió             Alagoas     957 916
16       17    Campo Grande  Mato Grosso do Sul     898 100
17       18     São Gonçalo      Rio de Janeiro     896 744
18       19        Teresina               Piauí     866 300
19       20     João Pessoa             Paraíba     833 932

In [8]:
dados_populacao.dtypes

ranking       int64
municipio    object
uf           object
populacao    object
dtype: object

In [9]:
# substituindo os espaços nos dados de populacao por nada
# uso de 'astype' para converter os dados para o tipo inteiro

dados_populacao['populacao'] = dados_populacao['populacao'].str.replace(r'\s', '', regex=True).astype(int)

In [10]:
dados_populacao

     ranking       municipio                uf  populacao
0          1       São Paulo         São Paulo   11451999
1          2  Rio de Janeiro    Rio de Janeiro    6211223
2          3        Brasília  Distrito Federal    2817381
3          4       Fortaleza             Ceará    2428708
4          5        Salvador             Bahia    2417678
..       ...             ...               ...        ...
314      315      Manacapuru          Amazonas     101883
315      316          Balsas          Maranhão     101767
316      317         Lagarto           Sergipe     101579
317      318           Assis         São Paulo     101409
318      319       Itaperuna    Rio de Janeiro     101041

[319 rows x 4 columns]

### Cálculos estatísticos

In [11]:
media_total = dados_populacao['populacao'].mean()
mediana_total = dados_populacao['populacao'].median()

print(f'Media conjunto de dados completo: {media_total:,}\nMediana conjunto de dados completo: {mediana_total:,}')

Media conjunto de dados completo: 362,520.1724137931
Mediana conjunto de dados completo: 187,315.0

##### A média é uma métrica muito mais sensível a valores extremos (outliers)

##### O desvio padrão auxilia a identificar esses outliers

In [12]:
desvio_padrao = dados_populacao['populacao'].std()

print(f'Desvio Padrão conjunto de dados completo: {desvio_padrao:,}')

Desvio Padrão conjunto de dados completo: 792,866.9083592542

#### Filtrando valores extremos (que estão acima/abaixo de 2 vezes o desvio padrão)

In [13]:
limite_superior = media_total + 2*desvio_padrao
limite_inferior = media_total - 2*desvio_padrao

print(f'Serão excluídos os valores fora da faixa [{limite_inferior:,}, {limite_superior:,}]')

Serão excluídos os valores fora da faixa [-1,223,213.6443047153, 1,948,253.9891323016]

In [14]:
dados_populacao['dentro_da_faixa'] = dados_populacao['populacao'] <= limite_superior
dados_populacao

     ranking       municipio                uf  populacao  dentro_da_faixa
0          1       São Paulo         São Paulo   11451999            False
1          2  Rio de Janeiro    Rio de Janeiro    6211223            False
2          3        Brasília  Distrito Federal    2817381            False
3          4       Fortaleza             Ceará    2428708            False
4          5        Salvador             Bahia    2417678            False
..       ...             ...               ...        ...              ...
314      315      Manacapuru          Amazonas     101883             True
315      316          Balsas          Maranhão     101767             True
316      317         Lagarto           Sergipe     101579             True
317      318           Assis         São Paulo     101409             True
318      319       Itaperuna    Rio de Janeiro     101041             True

[319 rows x 5 columns]

In [15]:
dados_populacao_reduzido = dados_populacao[dados_populacao['dentro_da_faixa']]
dados_populacao_reduzido

     ranking     municipio                 uf  populacao  dentro_da_faixa
7          8      Curitiba             Paraná    1773718             True
8          9        Recife         Pernambuco    1488920             True
9         10       Goiânia              Goiás    1437366             True
10        11  Porto Alegre  Rio Grande do Sul    1332845             True
11        12         Belém               Pará    1303403             True
..       ...           ...                ...        ...              ...
314      315    Manacapuru           Amazonas     101883             True
315      316        Balsas           Maranhão     101767             True
316      317       Lagarto            Sergipe     101579             True
317      318         Assis          São Paulo     101409             True
318      319     Itaperuna     Rio de Janeiro     101041             True

[312 rows x 5 columns]

### Calculando medidas para o novo conjunto

In [16]:
media_reduzido = dados_populacao_reduzido['populacao'].mean()
mediana_reduzido = dados_populacao_reduzido['populacao'].median()

print(f'Media conjunto de dados reduzido: {media_reduzido:,}\nMediana conjunto de dados reduzido: {mediana_reduzido:,}')

Media conjunto de dados reduzido: 275,441.33653846156
Mediana conjunto de dados reduzido: 183,003.5

In [17]:
dados_populacao_reduzido['uf'].mode()

0    São Paulo
Name: uf, dtype: object

##### A moda indica o valor ou categoria que mais aparece em um conjunto de dados
##### Mais útil quando estamos fazendo perguntas sobre uma variável categórica/quantitativa

In [18]:
dados_populacao_reduzido['uf'].value_counts()

uf
São Paulo              77
Minas Gerais           33
Rio de Janeiro         27
Paraná                 22
Rio Grande do Sul      19
Bahia                  17
Pará                   15
Goiás                  15
Santa Catarina         14
Pernambuco             12
Maranhão               10
Espírito Santo          9
Ceará                   7
Mato Grosso             6
Sergipe                 4
Paraíba                 4
Rio Grande do Norte     4
Mato Grosso do Sul      3
Piauí                   2
Rondônia                2
Amapá                   2
Alagoas                 2
Tocantins               2
Amazonas                2
Roraima                 1
Acre                    1
Name: count, dtype: int64